### ISSUE TITLE
freshly pulled jekyll/builder does not contain bash, so not wirking with gitlab-ci

### ISSUE THREAD

**Issue by dennisschuerholz** [jekyll/docker#110]
If I use the current Version of the jekyll/builder image I cannot build my projetcs using gitlab-ci-multi-runner anymore as the image does not contain the bash anymore since 14e3ae06d324fa00ef6f7b375505754f2ed6e0ee.

**Comment by codybushnell** [comment]
Same issue here.

**Comment by envygeeks** [comment]
This was very much intentional as I do not wish to carry the dependency. I'm going to be honest that if Gitlab CI doesn't allow you to set a POSIX complaint shell then it's doing it wrong and this bug belongs to them as they really should have an option to set the shell or look for a POSIX shell and even be doing POSIX compliant shell code because no shell is the same if it's not POSIX.

Does Gitlab have none of this?

**Comment by tommueller** [comment]
@envygeeks do you have any idea on how to make this work w/o bash? Where would I need to make changes? In gitlab or in the gitlab-ci-file?

**Comment by envygeeks** [comment]
@tommueller upstream has reverted the removal of sudo and bash and brought it back, this ticket will be closed when a new image is pushed out by the bot in a few minutes.

**Comment by envygeeks** [comment]
This issue is fixed.
