### ISSUE TITLE
Cannot use 'grunt-contrib-imagemin' within this docker container

### ISSUE THREAD

**Issue by tommueller** [jekyll/docker#113]
Hey there,

thanks for the perfect container. I do have one problem though (using 3.1.3 since I haven't solved the missing bash issue yet), I cannot use the grunt-contrib-imagemin package to automatically minify my pictures during deployment.

I do get the following errors: http://pastebin.com/Z4Y6aya2

I played around adding stuff like 
`apk --update add alpine-sdk`
`apk --update add nasm`
`apk --update add autoconf`

etc. pp. it helped to resolve some of the issues, I was able to build the jpeg package, but not optipng.

Is there a better way to make this work?

**Comment by envygeeks** [comment]
You'll need to provide the actual logs.  The only thing I see wrong is the usage of alpine-sdk instead of just installing build-base directly avoding all the other unnecessary alpine dependencies.  The error is probably wrong and you can probably find more in the raw logs provided in the log file they point you to.

**Comment by envygeeks** [comment]
Hi, it has been more than 12 days without a response, I am closing this ticket.  If you have this problem again please comment and I'll happily continue to work with you on the problem if you provided the asked for informations.
