### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by rockygiglio** [jekyll/docker#128]
When trying to run the image on Docker for Windows 10 I get the following. I setup a directory with a sample jekyll site from which I am executing the docker command. For this example that is c:\users\rocky\jekyll. 

```
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p 127.0.0.1:4000:4000 jekyll/jekyll
Configuration file: none
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.02 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
Configuration file: none
jekyll 3.2.1 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/_site
sh: can't kill pid 32: No such process

```

**Comment by johannesgkp** [comment]
I got the same problem with docker toolbox on windows 8.1

**Comment by envygeeks** [comment]
Send `-e UID=yourMacOSUID` as far as the Windows problem, I'll look into that but I think I consider that a Docker bug, if it cannot route the UID in, there isn't much I can do about that, other than run as root I assume.

**Comment by mstred** [comment]
@rockygiglio, I think you're running into a volume path error. AFAIK, Windows doesn't offer support to Unix Shell command substitution, as well as env vars (since it uses `%VAR%` instead of `$VAR` or `${VAR}`). So `${pwd}` isn't a valid choice.

My way to get along this was putting an absolute path (yeah, I know it sucks... but it works) as the host value for `--volume`. To increase the [weirdness](http://stackoverflow.com/a/33151452), the `--volume` argument isn't capable to understand Windows' backslash for paths. In order to make it work, `C:\Users\` would be `//c/Users/`.

So you'd need to do something like this:

```bat
docker run --rm --label=jekyll --volume //c/Users/rocky/jekyll:/srv/jekyll -it -p 127.0.0.1:4000:4000 jekyll/jekyll
```

**Comment by envygeeks** [comment]
Yes, on Windows you'll need to make the path static or use Windows style substitutions.

**Comment by jerrac** [comment]
If anyone else ends up here after having issues with not being able to mkdir _site, use `-e JEKYLL_UID="$UID" -e JEKYLL_GID="$GID"`. That worked for me. 

The earlier comment about `-e UID=youMacOSUID` is apparently out of date.

**Comment by matthiaslischka** [comment]
Today I had to - out of the blue - give permissions. Not sure what changed. The [same docker-compose](https://github.com/matthiaslischka/matthiaslischka.at/blob/master/docker-compose.yml) worked a month ago like a charm... But today I got this "Permission denied". Deleting the volumes and docker images and restarting docker-compose did not fix the problem.

`chown -R jekyll:jekyll /srv/jekyll`

**Comment by envygeeks** [comment]
Nothing has changed. Unless you can provide more information I’m to assume this is a system problem.

**Comment by matthiaslischka** [comment]
I thought so myself. Just wanted to share my finding since this "permission denied" seems to pop up every now and then. In fact that anyway only fixed the "permission denied" issue. The container user still can't see any files in the mounted volume, only the created and empty _site folder. Not sure what I changed at the system. I wanted to utilize docker to prevent my page from being depending on a flaky dev machine. So much for that... XD

**Comment by envygeeks** [comment]
If you don't have an organization public docker account, you can build a Docker image based on mine, and copy your site into `/srv/jekyll` and push it up to Dockerhub, and just don't mount anything into there, and boot it up as normal without volumes.

```
FROM jekyll/jekyll
COPY . /srv/jekyll
```

**Comment by karlbrown-va** [comment]
I experienced permissions issues with 4.2.0 similar to the above, to fix I did the following in my gnu makefile:
(at the top)
```
UID    := $(shell id -u)
GID    := $(shell id -g)
```

In the docker command:
```
docker run -e JEKYLL_UID=$(UID) -e JEKYLL_GID=$(GID) ...
```
Thanks @jerrac for the solution.
