### ISSUE TITLE
Dependency  error when using this theme http://webjeda.com/cards/

### ISSUE THREAD

**Issue by brocchini** [jekyll/docker#136]
Disclaimer: I have never programmed in Ruby, so pardon my ignorance, but I'm an experienced in a few other languages.

If anyone could kindly give any hint, I'd be very appreciated.

I tried to run a container using the theme above and ran into error below:
```
 sudo docker logs f9c
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Installing public_suffix 2.0.4
Using colorator 1.1.0
Using ffi 1.9.14
Using forwardable-extended 2.6.0
Using sass 3.4.22
Installing rb-fsevent 0.9.8
Installing kramdown 1.13.1
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using bundler 1.12.5
Installing addressable 2.5.0
Using rb-inotify 0.9.7
Using pathutil 0.14.0
Installing jekyll-sass-converter 1.5.0
Using listen 3.0.8
Using jekyll-watch 1.5.0
Installing jekyll 3.3.1
Installing jekyll-feed 0.8.0
Installing minima 2.1.0
Bundle complete! 3 Gemfile dependencies, 21 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from minima:

----------------------------------------------
Thank you for installing minima 2.0!

Minima 2.0 comes with a breaking change that
renders '<your-site>/css/main.scss' redundant.
That file is now bundled with this gem as
'<minima>/assets/main.scss'.

More Information:
https://github.com/jekyll/minima#customization
----------------------------------------------

Configuration file: /srv/jekyll/_config.yml
Configuration file: /srv/jekyll/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
jekyll 3.3.1 | Error:  jekyll-paginate
sh: can't kill pid 687: No such process
```

**Comment by yuckfood-ccuser** [comment]
sorry, I don't know much Ruby. but I know where you could learn it.

On Fri, Dec 16, 2016 at 11:20 AM Mozart Brocchini <notifications@github.com>
wrote:

Disclaimer: I have never programmed in Ruby, so pardon my ignorance, but
I'm an experienced in a few other languages.

If anyone could kindly give any hint, I'd be very appreciated.

I tried to run a container using the theme above and ran into error below:

 sudo docker logs f9c
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Installing public_suffix 2.0.4
Using colorator 1.1.0
Using ffi 1.9.14
Using forwardable-extended 2.6.0
Using sass 3.4.22
Installing rb-fsevent 0.9.8
Installing kramdown 1.13.1
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using bundler 1.12.5
Installing addressable 2.5.0
Using rb-inotify 0.9.7
Using pathutil 0.14.0
Installing jekyll-sass-converter 1.5.0
Using listen 3.0.8
Using jekyll-watch 1.5.0
Installing jekyll 3.3.1
Installing jekyll-feed 0.8.0
Installing minima 2.1.0
Bundle complete! 3 Gemfile dependencies, 21 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from minima:

----------------------------------------------
Thank you for installing minima 2.0!

Minima 2.0 comes with a breaking change that
renders '<your-site>/css/main.scss' redundant.
That file is now bundled with this gem as
'<minima>/assets/main.scss'.

More Information:https://github.com/jekyll/minima#customization
----------------------------------------------

Configuration file: /srv/jekyll/_config.yml
Configuration file: /srv/jekyll/_config.yml
  Dependency Error: Yikes! It looks like you don't have
jekyll-paginate or one of its dependencies installed. In order to use
Jekyll as currently configured, you'll need to install this gem. The
full error message from Ruby is: 'cannot load such file --
jekyll-paginate' If you run into trouble, you can find helpful
resources at http://jekyllrb.com/help/!
jekyll 3.3.1 | Error:  jekyll-paginate
sh: can't kill pid 687: No such process
[mbro8122@ip-10-168-140-35 ~]$ Connection to
lx238smxide02d.aws.na.sysco.net closed by remote host.
Connection to lx238smxide02d.aws.na.sysco.net closed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jekyll/docker/issues/136>, or mute the thread

**Comment by Dennis-Mayk** [comment]
Your problem is that you don't have the pagination plugin installed which is required by your theme to work properly. Run: `gem install jekyll-paginate` to install the package. Hope that helps

**Comment by brocchini** [comment]
@Dennis-Mayk  thanks for the suggestion, but my `_config.yml` already declares that gem like so:
```
# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]
```
Shouldn't this be enough ?

**Comment by envygeeks** [comment]
@brocchini you also need to add jekyll-paginate to your gemfile.

**Comment by brocchini** [comment]
@envygeeks which gemfile ?
I don't currently have one, since I am running the docker image from this Github repo, do I have to overwrite  this file `https://github.com/jekyll/docker/blob/master/Gemfile ` and rebuild the image ?

**Comment by envygeeks** [comment]
No, you need to add a Gemfile to your Jekyll project and add "jekyll-paginate" to it.  Jekyll and this image do not install dependencies from the "gems" key in `_config`.  However, I recently made some changes to this image so maybe it'll work now that I've made those changes.
