### ISSUE TITLE
[Question] Bundle Update?

### ISSUE THREAD

**Issue by wandersonwhcr** [jekyll/docker#148]
Why does docker image use `bundle update` and not `bundle install`?

https://github.com/jekyll/docker/blob/f9945e14ec54df730c36d3cf23410c29013df0b7/repos/jekyll/copy/all/usr/local/bin/jekyll#L37

I have a `Gemfile.lock` in my repository and when I run this docker image, that file is always changed. I currently know that when finished, that file is reverted. But, does this break `Gemfile.lock` principles, right?

http://stackoverflow.com/a/6927553

btw, ty for this image!

**Comment by envygeeks** [comment]
No, it doesn't. If it did then Bundler wouldn't have `bundle update` they would only have `bundle install` and `bundle restore` (like GoVendor and other GoLang tools,)  the principle of your Gemfile.lock is set by you via your Gemfile, and `bundle update` sticks to those rules.

We run `bundle update` because it's a personal preference.

**Comment by wandersonwhcr** [comment]
OK.

I'll fork you repo and use `bundle install` instead, because it's my personal preference.

BTW, ty!
