### ISSUE TITLE
Don't use ping to determine internet connectivity

### ISSUE THREAD

**Issue by olof** [jekyll/docker#154]
I use the jekyll docker image behind a firewall/proxy. #151 resulted in a change where a ping command is executed to determine if internet connectivity is available. We're not allowed to do ICMP against internet hosts, but we can do http requests via proxy. May I suggest changing this to a curl/wget call instead? Or make it possible to skip "probing" for internet connectivity, and just assume it (e.g. something like `docker run ... -e ASSUME_INTERNET=y ...`)?

Thanks!

**Comment by eldipa** [comment]
Hi! because I started #151 now I feel a little responsible of this issue too.

My best option to fix this is to use ```wget -s www.google.com```. 
The ```-s``` flag makes ```wget``` to check the existence of the resource without fetching it.

Someone have a better option?

Other good options that ran through my brain but, imho, they aren't good enough were:
 - ```apk update```:  the drawback is that it fetches all the URLs and times out in each one; too slow.
 - ```apk fetch ruby-dev```: because fetches a single resource is faster than the previous one but we need to pay the price of download a package and then to delete it after the test.
 - ```nslookup google.com 8.8.8.8```: even in proxied environments you should have access to a DNS resolver. If an external resolver like ```8.8.8.8``` is not allowed we can use the default resolver. The drawback of this is that some default resolvers are local (running in your box) and may response a query with a cached response without connecting outside and missing the whole point.

If there aren't objections, I can submit a PR with the fix using ```wget``` but I think that it is good to have a little of brainstorming before that.

Thanks!

**Comment by olof** [comment]
Thanks @eldipa! I really appreciate your analysis! I agree that the DNS approach would be problematic, our firewall will block outbound dns packets, so we can't rely on e.g. Google's resolvers. But your first approach sounds good to me.

**Comment by olof** [comment]
The issue is not solved by the 3d8f19b change, since this still requires direct connectivity to google.
