### ISSUE TITLE
jekyll/builder vs. jekyll/jekyll:builder

### ISSUE THREAD

**Issue by stv0g** [jekyll/docker#160]
Whats the difference?

In you latest fix for #159, jekyll/jekyll:builder was not updated.

**Comment by envygeeks** [comment]
Jekyll builder has stuff I did not wish to be in the main image at the time: https://github.com/jekyll/docker/blob/master/repos/builder/opts.yml but I don't know that matters anymore and they might merge eventually since our build system can alias across entire repositories.

As for jekyll/jekyll:builder not building, it's been added to the matrix.
