### ISSUE TITLE
Docker image broken: cp: can't stat 'Gemfile.lock': No such file or directory

### ISSUE THREAD

**Issue by tomdee** [jekyll/docker#161]
We use the v3.3.1 docker image, but it looks like that image has been changed under our feet (not a good practice). Would it be possible to keep past releases stable?

```
docker run --rm -ti -e JEKYLL_UID=`id -u` -v $PWD:/srv/jekyll jekyll/jekyll:3.3.1 jekyll clean
fetch http://mirror.envygeeks.io/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://mirror.envygeeks.io/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
fetch http://mirror.envygeeks.io/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://mirror.envygeeks.io/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://mirror.envygeeks.io/alpine/edge/main/x86_64/APKINDEX.tar.gz
v3.5.2-81-gf4d50b1370 [http://mirror.envygeeks.io/alpine/v3.5/main]
v3.5.2-81-gf4d50b1370 [http://mirror.envygeeks.io/alpine/v3.5/community]
v3.6.0_rc3-11-ge8bec87892 [http://mirror.envygeeks.io/alpine/edge/community]
v3.6.0_rc3-4-g4e87f352c9 [http://mirror.envygeeks.io/alpine/edge/testing]
v3.6.0_rc3-12-g6510cbf1b8 [http://mirror.envygeeks.io/alpine/edge/main]
OK: 18496 distinct packages available
OK: 256 MiB in 73 packages
cp: can't stat 'Gemfile.lock': No such file or directory
```

**Comment by envygeeks** [comment]
There are no new features, there are no changed entrypoints or surface API's that have changed so where is this "change under your feet" coming from? Regressions happen during internal refactoring sometimes, that's why you should always stage before deploying (while we are on the topic of generally bad practices :wink:)  

I'm sorry we had a regression and it's being fixed but this image is continuous and will continue to be for any version of Jekyll we currently consider supported. As far as regressions are concerned, I plan to add tests soon that enforce the features of this image soon, I just haven't had time to push them up, so that should make things more stable all around.

**Comment by envygeeks** [comment]
And by "enforce features" for the tests, I mean testing that things like what you experienced don't happen before deploying and stop the deploy before it can reach Docker Hub for GA.

**Comment by tomdee** [comment]
Thanks for the quick turnaround on the fix.
