### ISSUE TITLE
no npm installation

### ISSUE THREAD

**Issue by suskind** [jekyll/docker#176]
apparently alpine is not installing npm with nodejs

I'm using `FROM jekyll/jekyll:3.2.1` just because legacy (didn't tried latest), and with: 

```
RUN node --version
RUN npm --version
```

I've got 

```
Step 5/23 : RUN node --version
 ---> Running in 94f53922af03
v6.10.3
 ---> e7df21c1b6b1
Removing intermediate container 94f53922af03
Step 6/23 : RUN npm --version
 ---> Running in 75b950d8c941
/bin/sh: npm: not found
``` 

To fix this, I had to install nodejs-npm

`RUN apk add --no-cache --repository http://nl.alpinelinux.org/alpine/v3.6/main nodejs=6.10.3-r1 nodejs-npm=6.10.3-r1` 

Thank you

**Comment by envygeeks** [comment]
I didn't intend to make npm available because we provide node.js for Coffeescript/Jekyll-Assets mostly, is there any particular reason you would like it?  If I'm quite frank with the new Jekyll-Assets it will probably be necessary because all things considered it supports npm dependencies through Yarn.

**Comment by suskind** [comment]
In this case npm is used to install dev dependencies (grunt) and dependencies to run a small script "to do some required stuff" before jekyll build.
