### ISSUE TITLE
gem install json fails

### ISSUE THREAD

**Issue by mringwal** [jekyll/docker#187]
Hi there

When running the command from the README.md, the build fails setting up json. Any ideas?

$ export JEKYLL_VERSION=3.5
$ docker run --rm \
>   --volume=$PWD:/srv/jekyll \
>   -it jekyll/jekyll:$JEKYLL_VERSION \
>   jekyll build

The following gems are missing
 * addressable (2.3.8)
 * colorator (0.1)
 * colored (1.2)
 * concurrent-ruby (1.0.1)
 * deep_merge (1.0.0)
 * configure-s3-website (1.7.1)
 * dotenv (1.0.2)
 * execjs (2.5.2)
 * fastimage (1.9.0)
 * ffi (1.9.10)
 * sass (3.4.21)
 * jekyll-sass-converter (1.4.0)
 * rb-fsevent (0.9.7)
 * rb-inotify (0.9.7)
 * listen (3.0.6)
 * jekyll-watch (1.3.1)
 * kramdown (1.10.0)
 * liquid (3.0.6)
 * mercenary (0.3.5)
 * rouge (1.10.1)
 * jekyll (3.1.2)
 * rack (1.6.4)
 * sprockets (3.5.2)
 * sprockets-helpers (1.2.1)
 * tilt (2.0.2)
 * jekyll-assets (2.1.2)
 * json (1.8.3)
 * redcarpet (3.3.4)
 * thor (0.19.1)
 * s3_website (2.12.3)
 * uglifier (2.7.1)
Install missing gems with `bundle install`
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Fetching addressable 2.3.8
Installing addressable 2.3.8
Using bundler 1.15.4
Fetching colorator 0.1
Installing colorator 0.1
Fetching colored 1.2
Installing colored 1.2
Fetching concurrent-ruby 1.0.1
Installing concurrent-ruby 1.0.1
Fetching deep_merge 1.0.0
Installing deep_merge 1.0.0
Fetching dotenv 1.0.2
Installing dotenv 1.0.2
Fetching execjs 2.5.2
Installing execjs 2.5.2
Fetching ffi 1.9.10
Installing ffi 1.9.10 with native extensions
Fetching sass 3.4.21
Installing sass 3.4.21
Fetching rb-fsevent 0.9.7
Installing rb-fsevent 0.9.7
Fetching kramdown 1.10.0
Installing kramdown 1.10.0
Fetching liquid 3.0.6
Installing liquid 3.0.6
Fetching mercenary 0.3.5
Installing mercenary 0.3.5
Fetching rouge 1.10.1
Installing rouge 1.10.1
Using safe_yaml 1.0.4
Fetching rack 1.6.4
Installing rack 1.6.4
Fetching tilt 2.0.2
Installing tilt 2.0.2
Fetching json 1.8.3
Installing json 1.8.3 with native extensions
Fetching redcarpet 3.3.4
Installing redcarpet 3.3.4 with native extensions
Fetching thor 0.19.1
Installing thor 0.19.1
Fetching fastimage 1.9.0
Installing fastimage 1.9.0
Fetching configure-s3-website 1.7.1
Installing configure-s3-website 1.7.1
Fetching rb-inotify 0.9.7
Installing rb-inotify 0.9.7
Fetching jekyll-sass-converter 1.4.0
Installing jekyll-sass-converter 1.4.0
Fetching sprockets 3.5.2
Installing sprockets 3.5.2
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/json-1.8.3/ext/json/ext/generator
/usr/local/bin/ruby -r ./siteconf20171006-33-cytpnj.rb extconf.rb
creating Makefile

current directory: /usr/local/bundle/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /usr/local/bundle/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c: In function 'generate_json':
generator.c:861:25: error: 'rb_cFixnum' undeclared (first use in this function)
     } else if (klass == rb_cFixnum) {
                         ^~~~~~~~~~
generator.c:861:25: note: each undeclared identifier is reported only once for each function it appears in
generator.c:863:25: error: 'rb_cBignum' undeclared (first use in this function)
     } else if (klass == rb_cBignum) {
                         ^~~~~~~~~~
generator.c: At top level:
cc1: warning: unrecognized command line option '-Wno-self-assign'
cc1: warning: unrecognized command line option '-Wno-constant-logical-operand'
cc1: warning: unrecognized command line option '-Wno-parentheses-equality'
make: *** [Makefile:242: generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/bundle/gems/json-1.8.3 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.4.0/json-1.8.3/gem_make.out

An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.

In Gemfile:
  uglifier was resolved to 2.7.1, which depends on
    json

**Comment by envygeeks** [comment]
You should update your version of Uglifier.  It's far too old, Jekyll Assets 2 will work with any verion of Uglifier including the latest release, other than that this is an issue for https://github.com/flori/json unfortunately but I don't assume they would want to fix this problem since it's a far release (but you might try filing a ticket with them just incase.)

Sorry I could not help past asking you to update uglifier and filing a gem in the proper repository.

**Comment by mringwal** [comment]
Thanks for answering. 

I'm a total stranger to Ruby and failed to run get the dependencies for Jekyll right with Ruby 2.1 + gem (SSL issue downloading anything), Ruby 2.2+ (compile error), so I've tried the Docker container as everything should be contained in the docker image (without me touching anything inside the container).

If you or anyone else runs the recommended docker command, he/she should get the same behaviour, no? If something inside the docker image needs an update, shouldn't this be part of the docker image construction?

**Comment by envygeeks** [comment]
Our Docker image does provide everything that you need to run Jekyll.  It does not however provide extra gems that you choose to carry into the Docker image yourself (such as Jekyll-Assets -- through a `Gemfile`.)  We only attempt to install your extra dependencies, and provide a very minimal set of libraries to help you install them... updating is up to you (as in managing your own dependencies if you choose to carry them)  We do expose tools to do that if you wish:

```bash
docker run --volume=$PWD:/srv/jekyll --rm -it jekyll/jekyll depends update
```

We also expose the official `bundle` command without our depends wrapper, use at your own risk, as we do shim stuff to make your life easier so `depends` is where the money is at... it will call `bundle` on your behalf once it's done setting up.

Aside from that. If you need a special library to install something, it is up to you to provide that, and our documentation notes how to do that.  If you have an error installing a gem, that error belongs to the Gem, not to us, we didn't program their software.  Our image by default does provide the latest version of JSON:

```
docker run --rm -it jekyll/jekyll gem list | grep -i json
json (default: 2.0.4)
```

However, because you chose to provide a `Gemfile` and a `Gemfile.lock` with outdated versions, we did as you requested, and tried to install the gems you needed, and it error'd, your only option past that point is to update your `Gemfile.lock` (see above) or to delete your `Gemfile.lock` (which should update everything defacto unless you do strict versioning,) or to file a ticket with the author of JSON an hope they release a new version of 1.8 so it works (though there are even versions of 1.8 after the version you have so I assume it was already resolved.)

**Comment by envygeeks** [comment]
I have updated the documentation to note that people can use our image to update if they need.

**Comment by mringwal** [comment]
Thank you very much for the detailed answer. The missing piece for me was that the Gemfile from the project I wanted to process did add additional Gems. I assumed that the errors were related from fetching the dependencies for Jekyll itself. Now, your first answer totally makes sense. Sorry for keeping you busy.

I was just about to suggest adding a paragraph about this on the main readme, but you've beat me to his. Thanks!
