### ISSUE TITLE
theme not working in pages tag

### ISSUE THREAD

**Issue by simonvanderveldt** [jekyll/docker#194]
Using the current tag (`3e2c3988e7cb`) of the `jekyll/jekyll:pages` image I'm unable to get Jekyll to use the theme I've defined in `_config.yml`

My `_config.yml` looks like this:
```
theme: jekyll-theme-minimal
```

Since the `jekyll/jekyll:pages` image already includes the `github-pages` gem, which among other things installs the `jekyll-theme-minimal` gem I expected this to just work.

Am I doing something wrong or is this somehow broken?

**Comment by envygeeks** [comment]
I don't know if you're doing something wrong tbqf, I don't use Github Pages, it's gem or anything along those lines, we do nothing special for Github pages tag other than install Github-Pages and match it's dependency tree.

If you provide a repository, I'm happy to see if I can figure out what's wrong. Otherwise, this might have to land on Jekyll/Github-Pages, since we don't do anything special, if it works in without `:pages` tag, it should work with `:pages` tag.  If it works without `github-pages` it should work with `github-pages`.

I do know this much, if you mix a Gemfile into the image, and don't include that theme or `Github-Pages` you will not get access to the stuff that we install by default, since we isolate your dependency off unless they match, and so does Bundler, that is the nature of Ruby and it's dependency management.

**Comment by simonvanderveldt** [comment]
@envygeeks Thanks for the quick response!

A minimal example can be found here https://github.com/simonvanderveldt/jekyll-pages-test
This results in this rendered site http://simonvanderveldt.nl/jekyll-pages-test/ but when run locally using the `jekyll/jekyll:pages` images returns an unstyled document 
![image](https://user-images.githubusercontent.com/204286/32808054-31fc7fbc-c992-11e7-84ff-0f3cf115eb68.png)

**Comment by envygeeks** [comment]
Once the CI is done building you can update and your site should work as expected.

**Comment by simonvanderveldt** [comment]
@envygeeks Thanks for the quick fix! It's working now.

I did have to install `git` to make it work because `git` isn't included in the image and apparently the github-metadata gem needs it, similar to https://github.com/jekyll/github-metadata/issues/57.

But that seems to be something that should be fixed on the github-metadata side instead of adding `git` to this image so I'll create an issue there.

**Comment by envygeeks** [comment]
The only way they could fix that is to either 1.) Parse the config file (that's easy,) or to add a configuration option (what they should have originally done as a fallback... since they are working with Github remote, it would have made sense to have that.) That said, I doubt they'll fix that issue, so I've added Git to the image.
