### ISSUE TITLE
Permission denied @ rb_sysopen

### ISSUE THREAD

**Issue by alberto56** [jekyll/docker#32]
Hi, I recently started getting the following error:

Permission denied @ rb_sysopen 

I initially thought it was related to https://github.com/jekyll/docker/issues/31 but it seems that it is a separate issue.

I have two CircleCI builds of the exact same commit here,

 * the [first from one month ago](https://circleci.com/gh/dcycleproject/dcyclebox/82) uses v. 91c3c267a129 of jekyll/jekyll and is working fine.
 * the [second from today](https://circleci.com/gh/dcycleproject/dcyclebox/91) uses v. 5f8dc0edd59c of jekyll/jekyll and is failing with `jekyll 2.5.3 | Error:  Permission denied @ rb_sysopen - /srv/jekyll/_site/Dcycle-Dockerfile-jekyll`. 
 * The code is [here](https://github.com/dcycleproject/dcyclebox).
 * I can't reproduce this locally (on my CoreOS VM), only on CircleCI.

**Comment by envygeeks** [comment]
@alberto56 this was actually already fixed in a one off commit and should be available soon,  you can see that commit here: https://github.com/jekyll/docker/commit/b12cd8097d4634f7cab4f30f12c417f2054ab96e -- for some reason you are not able to adjust the permissions on a volume in a sub image, even when we do `ONBUILD` so we removed the volume entirely.

**Comment by alberto56** [comment]
Thanks again for your super-quick response. This is now fixed.
