### ISSUE TITLE
Don't use chown on /srv/jekyll

### ISSUE THREAD

**Issue by Stealthii** [jekyll/docker#35]
Changing ownership permissions affects ownership of the files on the host system. As per the [running guide](https://github.com/jekyll/docker#running), the line `chown jekyll:jekyll /srv/jekyll && \` sets the ownership of whatever directory I mounted to a user of UID 1000.

If it is absolutely required to own this directory, maybe consider not using a user account within the container at all.

**Comment by envygeeks** [comment]
Our running guide mentions nothing about chown and it never will.  This image is designed for the average user who wants things working in an orderly fashion and we try our best to guarantee that.  To do what you wish without any valid reason will only sacrifice what others needed and wanted so this is a WONTFIX unless you can come up with a very very good and valid reason as to why it should change.

**Comment by Stealthii** [comment]
I wasn't clear, apologies. The container itself, runs that command.

The running guide suggests you do the following to get a running Jekyll container within your current directory:
```
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll \
  -t -p 127.0.0.1:4000:4000 jekyll/jekyll jekyll s
```

Doing this on any standard system will change the permissions of my entire working directory, on my host system to be owned by the user at 1000. I do not like this, and I don't think it should be regular behaviour. The container should not need to change permission of, or mess with my local files, in order to serve a simple Jekyll instance container with the built version of my site.

**Comment by parkr** [comment]
Yeah I think we shouldn't need to chown if we can match the host uid to the docker uid

**Comment by envygeeks** [comment]
To put it flatly: not easily.  Unless somebody is willing to submit a patch upstream to `envygeeks/alpine` and `envygeeks/ubuntu` through `envygeeks/docker` `vendor/common` to create a helper (with tests, it needs tests) this will not happen.  Our images do work in line with standard Docker behavior, we run as an unprivileged user, we need to chown and own the folder to bundle install if you ask us to, and even if we don't, your `_site` folder will be owned by 1000/1000 or 0/0.

Technically we can track the UID/GID and modify the system UID and GID on the fly (that is if Docker even passes it via the mounted volume): https://github.com/envygeeks/docker/blob/master/vendor/common/usr/local/share/docker/helpers#L182 and that is upstream, but we need a helper to parse and pull the UID and GID of the users and it's not work I'm willing to do because we currently fall in line with Docker's native environment (Linux) and use standard user 1000/1000.  We will never run Jekyll as root, even in a container.

**Comment by parkr** [comment]
The chown-ing in question is at the bottom of this file: https://github.com/jekyll/docker/blob/master/Dockerfile

Is there a workaround for now to chown the /srv/Jekyll or to leave the host files untouched?

**Comment by envygeeks** [comment]
The chown in question is here: https://github.com/jekyll/docker/blob/master/copy/etc/startup1.d/01-srv-jekyll-permissions that said, you have two options (both of which I make extra easy for any user who needs to customize our image) delete `copy/etc/startup1.d/01-srv-jekyll-permissions` and `script/build jekyll:whatever-tag-you-use` or... modify the Dockerfile and change the UID and GID `script/build jekyll:whatever-tag-you-use`...

In the end, I'm opting to enforce a conformity to ensure workability than to let things go and then deal with a ton of tickets that ask why this isn't working and that isn't working and why this doesn't behave right and why that doesn't behave right.

I'm not against trying to ensure that the UID can remain the same, I am just not willing to put in the work for it (and it needs to be done upstream where the helpers are) because I already have enough on my backlog and since there are plenty of ways to work around it in the meantime it's a super-low priority thing without help.

**Comment by envygeeks** [comment]
Hulk: +split-backlog/jekyll:backlog/docker +envygeeks/docker#1 : This ticket is being split

This ticket is being split into two pieces, one where we only modify our necessary files and folders (_site and vendor/bundle) and the aforementioned ticket where we grab the UID/GID of the user to modify our runtime UID/GID so that when we chown you get consistency.  The former is a jekyll/docker issue the latter is an upstream issue.
