### ISSUE TITLE
Add option to not start nginx

### ISSUE THREAD

**Issue by iBobik** [jekyll/docker#38]
We use this image only for running builds, not for serve sites. So nginx inside image slows down building and adds not relevant log messages.

How about to add env variable telling we do not need webserver?

**Comment by envygeeks** [comment]
How exactly does something that boots instantly and uses no CPU on wait slow down tests?

**Comment by iBobik** [comment]
I am not sure how to disable it, so I dont have comparation. It just seems logical (because it prints some messages to build log) :-)

**Comment by envygeeks** [comment]
I don't know if I accept that logic because that is a broad assumption that is uncorrelated and if logging does significantly slow you down that's not the fault of the image, that's a bug in Docker's logger because we tail wait and push to Docker.

I'm gonna have to think on this request because honestly removing nginx from the boot will be negligible to your performance and actually, it's the fastest process there is, that's why I accepted adding it in the first place for everybody who wanted our images to behave like Github.

**Comment by iBobik** [comment]
Ok, thank you for explanation. So I have one less think to care about :-)
