### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by iBobik** [jekyll/docker#39]
I am playing with building my own build of docker files, but I dont understand how ti run sync script properly.

What I am doing wrong? Are there some recomanded arguments?

```bash
$ ./script/sync
readlink: illegal option -- f
usage: readlink [-n] [file ...]
./script/sync: line 36: /Users/xxx/script/yaml: No such file or directory
$ cd script/
$ ./sync 
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
```

**Comment by iBobik** [comment]
Btw, also this did not worked:

```
$ ./script/sync beta
readlink: illegal option -- f
usage: readlink [-n] [file ...]
Unknown Image.
```

**Comment by parkr** [comment]
What system are you using?

**Comment by iBobik** [comment]
OS X El Capitan

**Comment by envygeeks** [comment]
All should be well for you.  Odd that OS X doesn't follow standard readlink behavior but who am I to fight it's craziness (even busybox supports -f)

**Comment by iBobik** [comment]
It seems problem is not solved:

```
$ ./script/sync latest
Unknown Image.
$ ./script/sync
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
$ git log
commit 49aac8d3f3e57e01e24718db28df3b8a2c067abd
Author: Jordon Bedwell <jordon@envygeeks.io>
Date:   Sat Oct 17 18:01:13 2015 -0500

    Fix #39: Remove -f and rely on simple readlink behavior.
```

**Comment by envygeeks** [comment]
I'm gonna be honest, I don't know if I'm willing to dumbify my scripts because OS X can't get their shit together and keep in line with the basics from the 80's

**Comment by envygeeks** [comment]
I pushed another commit, see if that fixes it.  I don't know how developers can live with those quirks.

**Comment by iBobik** [comment]
:-D

I undestand you. But reality is that there are people using OS X and that different systems behaves differently. And my experience is that nobody follows standards exacly, including Linux (if we agree POSIX is the right standard).

**Comment by iBobik** [comment]
Seems it is building, but only if I don't specify tag:
```
$ ./script/sync
$ ./script/sync latest
Unknown Image.
$ ./script/sync beta
Unknown Image.
```

Could I help you with some debuging?

**Comment by envygeeks** [comment]
Dash is a pretty strict POSIX shell... which Debian based systems use (I am a Debian/Ubuntu user,) now other distros get crazy and link to bash which to me reeks but we won't go into that craziness (cough: Arch) and some don't follow the FHS (cough: Fedora -- actually I don't mind Fedora not strcitly following the FHS, it's an intensely personal decision) but in my experience Debian tends to be the most strict as far as compliance and portability is concerned.

The problem here isn't POSIX though, it's the binaries that power that POSIX system which I guess relates to POSIX but POSIX guideline 11 clearly states that option order doesn't matter, so OS X really needs to get it together, but in all technical matters, we enforce an order ourselves in our optparse so we are no better here, but they are a low-level binary with the capability to be less strict (we need your options first because we need other options last -- like the tags -- that we pass via $@ so we need to shift.) and because we don't get access to array's we can't make it easy by looping with madness (but care!)

**Comment by envygeeks** [comment]
`script/sync` is not for building, you are doing it wrong.  You need to `script/build latest` technically `script/build` will sync for you so you don't even need to `script/sync`

**Comment by parkr** [comment]
To be fair, I also can't run this anymore.

```text
~/jekyll/docker#master$ ./script/build
/usr/local/var/rbenv/versions/2.1.6-github1/bin/erb:117:in `set_encoding': No such file or directory @ rb_sysopen - version=jekyll@3.0.0.pre.beta9 (Errno::ENOENT)
	from /usr/local/var/rbenv/versions/2.1.6-github1/bin/erb:117:in `run'
	from /usr/local/var/rbenv/versions/2.1.6-github1/bin/erb:154:in `<main>'
```

**Comment by envygeeks** [comment]
Open a new ticket @parkr and send `DEBUG=true` before you run the script and post a `gist`

**Comment by envygeeks** [comment]
Nevermind, it looks like I forgot to put the debug flag in script/build, one second.

**Comment by envygeeks** [comment]
Okay pull and try with `DEBUG=true script/build`

**Comment by iBobik** [comment]
It i building, but maybe not all is ok.

```
$ script/build latest
Building the image /jekyll:latest
repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"
```

**Comment by parkr** [comment]
`$user` isn't supplied.

**Comment by envygeeks** [comment]
I've added a default user to the script.
