### ISSUE TITLE
Native extension build errors

### ISSUE THREAD

**Issue by dhcole** [jekyll/docker#57]
Hi there. Thanks for making these docker images available! I'm running into two issues that seem related — I'm having trouble building a site with gems that require native extensions:

```
$ docker run --rm --volume=$(pwd):/srv/jekyll jekyll/jekyll:pages jekyll build
...
Installing nokogiri 1.6.6.4 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby -r ./siteconf20151124-36-1j6e6sf.rb extconf.rb --use-system-libraries=true --with-xml2-include=/usr/include/libxml2
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20151124-36-1n7jw8nnokogiri-1.6.6.4/gems/nokogiri-1.6.6.4 for inspection.
Results logged to /tmp/bundler20151124-36-1n7jw8nnokogiri-1.6.6.4/extensions/x86_64-linux/2.2.0/nokogiri-1.6.6.4/gem_make.out
An error occurred while installing nokogiri (1.6.6.4), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.6.4'` succeeds before bundling.
```

Also, I see something similar with a different tag of the docker image:

```
$ docker run --rm --volume=$(pwd):/srv/jekyll jekyll/jekyll:builder jekyll build
...
Installing redcarpet 3.2.3 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20151124-34-vgai0kredcarpet-3.2.3/gems/redcarpet-3.2.3/ext/redcarpet
/usr/bin/ruby -r ./siteconf20151124-34-3fh5do.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20151124-34-vgai0kredcarpet-3.2.3/gems/redcarpet-3.2.3 for inspection.
Results logged to /tmp/bundler20151124-34-vgai0kredcarpet-3.2.3/extensions/x86_64-linux/2.2.0/redcarpet-3.2.3/gem_make.out
An error occurred while installing redcarpet (3.2.3), and Bundler cannot
continue.
Make sure that `gem install redcarpet -v '3.2.3'` succeeds before bundling.
```

Here's the site / Gemfile I'm trying to use: https://github.com/dhcole/18f.gsa.gov/blob/staging/Gemfile

Do you have any suggests on what I might be doing wrong? Thanks!

**Comment by envygeeks** [comment]
To get on the right diagnostic track, does it attempt to install any apk (system) dependencies?

**Comment by dhcole** [comment]
Yes, it looks like it does, but perhaps out of order (with gems first)? Here's the full log:

https://gist.github.com/dhcole/e55fd5e903ae030ec9e8#file-docker-jekyll-log-L39

**Comment by envygeeks** [comment]
It looks out of order but it's actually an optimized boot to speed up most scenarios, that's actually it's second attempt to install where it does find the right recipe for you.

First we try to install your gems without c extensions and system libraries assuming you might have a simple Gemfile, this is uber fast... if that fails we assume you had a c extension and install common packages, setup your nokogiri so it knows where our libxml2 is and then install that way and if that fail we try one last time just to make sure it wasn't a Gem http error (they have a lot of problems in Australia still.)

Ultimately it looks like it completed and surfaced an error in Jekyll itself rather than with your Gem's

**Comment by dhcole** [comment]
Oh interesting. I see that now. The same command works locally and on our server, so perhaps something else is missing, like the ruby version being off.

Since the first error is expected behavior, I'll close this. Thanks for your help.

**Comment by envygeeks** [comment]
I think I'm gonna hold this open because that behavior isn't clearly defined to most people who aren't familiar with the internals of how we try to make our image fast, so I'm add a few echo's to make it noticeable to people!

**Comment by envygeeks** [comment]
Also @dhcole it looks like your problem is using the pages tag with an unlock Jekyll version, lock your Jekyll version to "~> 2.4.0" and the problem should go away, it's trying to install 3.0.0 https://github.com/dhcole/18f.gsa.gov/blob/staging/Gemfile#L5 and in the last iteration of 3.0.0 beta we switched to Documents (cc: @parkr for elaboration) so that's the problem, you are using an plugin that hasn't updated it's source so it's erroring out.

**Comment by dhcole** [comment]
Yea, good call. Will try pinning down the version. Thanks.

**Comment by parkr** [comment]
Installing 3.0.1 and running `bundle exec jekyll serve` worked just fine for me. The problem looks like issues installing C extensions, not with our Jekyll installation.

**Comment by envygeeks** [comment]
@parkr the problem ultimately turned to be an outdated plugin after I looked at the logs.
