### ISSUE TITLE
Add jekyll-watch by default

### ISSUE THREAD

**Issue by bexelbie** [jekyll/docker#79]
$ docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll   -it -p $(boot2docker ip):4000:4000     jekyll/jekyll
Using jekyll-feed (0.4.0)
Fetching: jekyll-paginate-1.1.0.gem (100%)
Installing jekyll-paginate (1.1.0)
Using kramdown (1.9.0)
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.578 seconds.
  Dependency Error: Yikes! It looks like you don't have jekyll-watch or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-watch' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
jekyll 3.0.1 | Error:  jekyll-watch
ok: down: /etc/startup3.d/nginx: 0s, normally up
sh: can't kill pid 25: No such process

**Comment by bexelbie** [comment]
Actually, jekyll-watch appears to be included as of the new image mentioned in #76   Therefore closing.

@envygeeks should this inclusion get mentioned in the README?

**Comment by envygeeks** [comment]
The new image your are speaking of was for #78.  #76 never got completed as I was consuming locked resources on the build server so it didn't build the image and probably won't until I manually build it and ship it. Sorry.

On the question about adding it to the README.  I don't think it should be added but I'm not against adding it if somebody wants to send a pull request.  The reason I say I don't think it should be added is because that list is directly tied to: https://github.com/jekyll/docker/blob/master/opts.yml#L74 -- we pretty much only list gems that we explicitly install directly so that you know what you might need to bring in.

**Comment by bexelbie** [comment]
Thanks for the clarification.  I am ok with omitting it for that reason and for the fact that it isn't one you would load to add functionality to your site, afaik.
