### ISSUE TITLE
Checks for pages tag fail

### ISSUE THREAD

**Issue by jabenninghoff** [jekyll/docker#83]
Both `/copy/all/etc/shutdown.d/01-gemfile` and `/copy/all/etc/startup1.d/03-gem-depends` appear to be checking to see if the image is `pages` by checking `/image`, which doesn't exist.

Specifically, these checks are not triggering on the pages variant:
```
/copy/all/etc/shutdown.d/01-gemfile:
if [ -f "/image" ] && [ "$(cat /image)" = "pages" ]; then exit 0
```
and
```
/copy/all/etc/startup1.d/03-gem-depends
if [ -f "/image" ] && [ "$(cat /image)" = "pages" ]; then
  echo "Github does not allow user dependencies."
  exit 0
fi
```

Is the intended behavior for `jekyll/docker:pages` to ignore the `Gemfile` if installed?

**Comment by envygeeks** [comment]
It's really irrelevant to me whether that check works or not, it was always a superficial enforcement, I do not plan to remove it, I will fix it, but whether or not it's broken because we adjusted the Dockerfile doesn't matter at the end of the day because the user will just switch to another tag to get what they want. So I never really bothered to enforce any amount of security testing on it.

**Comment by envygeeks** [comment]
I shouldn't say irrelevant because I do care that it's broken, I guess a better phrase would be, I never considered it a critical problem even though I knew it was broken.

**Comment by envygeeks** [comment]
Thanks for reporting this issue and contributing.  Your issue is now fixed and released.
