### ISSUE TITLE
Bug in /etc/startup1.d/03-gem-depends

### ISSUE THREAD

**Issue by thommeo** [jekyll/docker#86]
Problem:
Error: /etc/startup1.d/03-gem-depends: line 1: install_user_pkgs_from_file: not found

Solution:
sed -i 's/install_user_pkgs_from_file/docker-helper install_from_apk_file/g' /etc/startup1.d/03-gem-depends

**Comment by envygeeks** [comment]
The bug exists but your fix is incorrect, the fix is to push it through `docker-helper`

**Comment by envygeeks** [comment]
Let me clarify, upstream `envygeeks/alpine`, `envygeeks/ubuntu` provide `docker-helper install_user_pkgs_from_file` we just forgot to push it through Docker helper, we don't directly access `install_from_apk_file` because we want this image agnostic in-case we move back to Ubuntu so we always hit the outter API that wraps that and `install_from_apt_file`.

**Comment by thommeo** [comment]
ok )

**Comment by envygeeks** [comment]
Already resolved, thanks for reporting this!
